### ISSUE TITLE
InvalidParameterType: Expected params.Body to be a string, Buffer, Stream, Blob, or typed array object

### ISSUE THREAD

**Issue by kinowarrior** [mavi888/manning-learning-serverless-resizer-service#1]
Using 

```
 sls --version                      
1.41.1
```

Which in turn uses node.js aws-sdk version:

```
cd ~/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/node_modules/aws-sdk\n
 
cat package.json | grep aws-sdk                
  "_from": "aws-sdk@^2.430.0",
  "_id": "aws-sdk@2.445.0",
```

Getting the following error when running the code in this repo:

   ```
{ InvalidParameterType: Expected params.Body to be a string, Buffer, Stream, Blob, or typed array object
    at ParamValidator.fail (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validatePayload (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:255:10)
    at ParamValidator.validateScalar (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:133:21)
    at ParamValidator.validateMember (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:94:21)
    at ParamValidator.validateStructure (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:75:14)
    at ParamValidator.validateMember (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:125:42)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
  message: 'Expected params.Body to be a string, Buffer, Stream, Blob, or typed array object',
  code: 'InvalidParameterType',
  time: 2019-05-08T18:36:25.595Z }
```

The code deploys but when the resizer lambda function executes, the above happens.

Thought maybe it was `data.Body` on [this line](https://github.com/mavi888/manning-learning-serverless-resizer-service/blob/master/resizer.js#L11) but the [API docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getObject-property) for v2.4 seem to suggest that should be correct:

> Parameters:
> 
> err (Error) — the error object returned from the request. Set to null if the request is successful.
> data (Object) — the de-serialized data returned from the request. Set to null if a request error occurs. The data object has the following properties:
> Body — (Buffer(Node.js), Typed Array(Browser), ReadableStream)

 Tried googling but still unsure at this point. Any thoughts much appreciated?

**Comment by kinowarrior** [comment]
Ah ok, this looks related to [this comment](https://github.com/mavi888/manning-learning-serverless-resizer-service/commit/84b700d863b4e05f1bfdbc5017ca9fb1333354f1#commitcomment-30037223).

Testing now...

**Comment by kinowarrior** [comment]
Yes, that solved it. Used:

```
 .getBufferAsync(Jimp.MIME_JPEG, (err, buffer) => {
```
